name: CI

on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.0"
          - "1" # automatically expands to the latest stable 1.x release of Julia
          - nightly
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
          - x86
        # 32-bit Julia binaries are not available on macOS
        exclude:
          - os: macOS-latest
            arch: x86

    steps:
      - name: Checkout Example.jl
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          repository: julia-actions/Example.jl

      - name: Verify that test output file does not exist yet
        run: test ! -f "$HOME/julia-runtest"
        shell: bash

      - name: Checkout julia-runtest
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          path: ./.github/actions/julia-runtest

      - uses: julia-actions/setup-julia@f40c4b69330df1d22e7590c12e76dc2f9c66e0bc
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      - uses: julia-actions/julia-buildpkg@00f9fd6b2600be0a8d80566dd4d4d2389b3468eb

      - uses: ./.github/actions/julia-runtest

      - uses: julia-actions/julia-processcoverage@03114f09f119417c3242a9fb6e0b722676aedf38

      - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d
        with:
          file: lcov.info

      - name: Verify that test output file exists
        run: test -f "$HOME/julia-runtest"
        shell: bash
